"""Additional job listings surfaced on later auto-search cycles."""

from typing import Any, Dict, List

EXTENDED_JOB_POOL: List[Dict[str, Any]] = [
    {
        "source": "linkedin",
        "title": "Senior C# Engineer",
        "company": "Razorpay",
        "location": "Bangalore",
        "salary": "18-26 LPA",
        "description": "Build payment platform services using C#, .NET Core, microservices, and Azure.",
        "url": "https://www.linkedin.com/jobs/search/?keywords=razorpay%20csharp",
        "tech_stack": ["C#", ".NET Core", "Microservices", "Azure"],
    },
    {
        "source": "linkedin",
        "title": "Python AI Developer",
        "company": "PhonePe",
        "location": "Bangalore",
        "salary": "20-28 LPA",
        "description": "Develop AI features with Python, LangChain, LLMs, and production ML pipelines.",
        "url": "https://www.linkedin.com/jobs/search/?keywords=phonepe%20python%20ai",
        "tech_stack": ["Python", "AI", "LangChain", "Machine Learning"],
    },
    {
        "source": "indeed",
        "title": "Lead .NET Developer",
        "company": "Freshworks",
        "location": "Bangalore",
        "salary": "16-24 LPA",
        "description": "Lead SaaS development with C#, ASP.NET Core, and cloud-native architecture.",
        "url": "https://www.indeed.co.in/jobs?q=freshworks+.net",
        "tech_stack": ["C#", ".NET", "ASP.NET Core", "SaaS"],
    },
    {
        "source": "indeed",
        "title": "Machine Learning Engineer",
        "company": "Nvidia India",
        "location": "Bangalore",
        "salary": "22-35 LPA",
        "description": "Python ML engineer for GPU-accelerated AI workloads and model optimization.",
        "url": "https://www.indeed.co.in/jobs?q=nvidia+ml+engineer",
        "tech_stack": ["Python", "Machine Learning", "Deep Learning", "CUDA"],
    },
    {
        "source": "naukri",
        "title": "C# Software Developer",
        "company": "SAP Labs India",
        "location": "Bangalore",
        "salary": "14-22 LPA",
        "description": "Enterprise software development with C#, .NET, and SQL Server.",
        "url": "https://www.naukri.com/sap-csharp-jobs-bangalore",
        "tech_stack": ["C#", ".NET", "SQL Server", "Enterprise"],
    },
    {
        "source": "naukri",
        "title": "AI Engineer",
        "company": "Intel India",
        "location": "Bangalore",
        "salary": "18-28 LPA",
        "description": "Python AI engineer for computer vision and edge AI solutions.",
        "url": "https://www.naukri.com/intel-ai-engineer-bangalore",
        "tech_stack": ["Python", "AI", "Computer Vision", "Edge AI"],
    },
    {
        "source": "company_websites",
        "title": "Backend Engineer - C#",
        "company": "PayPal India",
        "location": "Bangalore",
        "salary": "20-30 LPA",
        "description": "Payments backend with C#, .NET, distributed systems, and high availability.",
        "url": "https://careers.paypal.com/",
        "tech_stack": ["C#", ".NET", "Distributed Systems", "Payments"],
    },
    {
        "source": "company_websites",
        "title": "Senior Python Engineer",
        "company": "Zoho",
        "location": "Bangalore",
        "salary": "12-18 LPA",
        "description": "Python backend engineer for SaaS products using Django and PostgreSQL.",
        "url": "https://www.zoho.com/careers/",
        "tech_stack": ["Python", "Django", "PostgreSQL", "Backend"],
    },
    {
        "source": "linkedin",
        "title": ".NET Core Developer",
        "company": "Meesho",
        "location": "Bangalore",
        "salary": "14-20 LPA",
        "description": "E-commerce platform development with C# and .NET Core microservices.",
        "url": "https://www.linkedin.com/jobs/search/?keywords=meesho+.net",
        "tech_stack": ["C#", ".NET Core", "Microservices", "E-commerce"],
    },
    {
        "source": "indeed",
        "title": "Python Backend Engineer",
        "company": "Cred",
        "location": "Bangalore",
        "salary": "18-26 LPA",
        "description": "Fintech backend with Python, FastAPI, and data-intensive services.",
        "url": "https://www.indeed.co.in/jobs?q=cred+python",
        "tech_stack": ["Python", "FastAPI", "Backend", "Fintech"],
    },
    {
        "source": "naukri",
        "title": "Senior Software Engineer - Python",
        "company": "Atlassian",
        "location": "Bangalore",
        "salary": "22-32 LPA",
        "description": "Python engineer for developer tools and cloud collaboration products.",
        "url": "https://www.naukri.com/atlassian-python-bangalore",
        "tech_stack": ["Python", "Cloud", "Developer Tools", "Backend"],
    },
    {
        "source": "company_websites",
        "title": "C# Full Stack Developer",
        "company": "Mastercard India",
        "location": "Bangalore",
        "salary": "16-24 LPA",
        "description": "Full stack fintech apps with C#, .NET, React, and secure APIs.",
        "url": "https://careers.mastercard.com/",
        "tech_stack": ["C#", ".NET", "Full Stack", "Fintech"],
    },
    {
        "source": "linkedin",
        "title": "ML Engineer - Python",
        "company": "Groww",
        "location": "Bangalore",
        "salary": "16-24 LPA",
        "description": "ML models for fintech using Python, scikit-learn, and MLOps tooling.",
        "url": "https://www.linkedin.com/jobs/search/?keywords=groww+ml",
        "tech_stack": ["Python", "Machine Learning", "MLOps", "Fintech"],
    },
    {
        "source": "indeed",
        "title": "C# Developer",
        "company": "Dell Technologies",
        "location": "Bangalore",
        "salary": "12-18 LPA",
        "description": "Enterprise tooling with C#, WPF, and Windows services integration.",
        "url": "https://www.indeed.co.in/jobs?q=dell+csharp",
        "tech_stack": ["C#", ".NET", "WPF", "Enterprise"],
    },
    {
        "source": "naukri",
        "title": "Python AI Engineer",
        "company": "Slice",
        "location": "Bangalore",
        "salary": "15-22 LPA",
        "description": "AI-powered credit products using Python, NLP, and recommendation systems.",
        "url": "https://www.naukri.com/slice-python-ai-bangalore",
        "tech_stack": ["Python", "AI", "NLP", "Recommendation"],
    },
    {
        "source": "company_websites",
        "title": "Software Engineer II - Python",
        "company": "VMware",
        "location": "Bangalore",
        "salary": "18-26 LPA",
        "description": "Cloud infrastructure automation with Python and Kubernetes.",
        "url": "https://careers.vmware.com/",
        "tech_stack": ["Python", "Kubernetes", "Cloud", "Automation"],
    },
    {
        "source": "linkedin",
        "title": "Senior .NET Architect",
        "company": "Ola",
        "location": "Bangalore",
        "salary": "20-30 LPA",
        "description": "Architecture for mobility platform using C#, .NET, and event-driven design.",
        "url": "https://www.linkedin.com/jobs/search/?keywords=ola+.net",
        "tech_stack": ["C#", ".NET", "Architecture", "Event-Driven"],
    },
    {
        "source": "indeed",
        "title": "Data Scientist",
        "company": "Myntra",
        "location": "Bangalore",
        "salary": "16-24 LPA",
        "description": "Fashion analytics with Python, pandas, and machine learning models.",
        "url": "https://www.indeed.co.in/jobs?q=myntra+data+scientist",
        "tech_stack": ["Python", "Data Science", "Machine Learning", "Analytics"],
    },
    {
        "source": "naukri",
        "title": "C# Backend Engineer",
        "company": "Rippling",
        "location": "Bangalore",
        "salary": "18-28 LPA",
        "description": "HR tech platform backend with C# and scalable API design.",
        "url": "https://www.naukri.com/rippling-csharp-bangalore",
        "tech_stack": ["C#", "Backend", "API", "SaaS"],
    },
    {
        "source": "company_websites",
        "title": "AI Platform Developer",
        "company": "Adobe India",
        "location": "Bangalore",
        "salary": "20-30 LPA",
        "description": "Creative AI tools with Python, deep learning, and cloud deployment.",
        "url": "https://careers.adobe.com/",
        "tech_stack": ["Python", "AI", "Deep Learning", "Cloud"],
    },
]
